platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('Flutter', 'podhelper'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end

  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
